language: node_js
node_js:
  - '12'

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"

script:
  - yarn run build
  - yarn run lint

notifications:
  email: false

branches:
  only: master
